version: "3.9"

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7080:8080" # Spark Master UI
      - "7077:7077" # Spark Master Port
    networks:
      - spark-net
    volumes:
      - ./jars/clickhouse-jdbc-0.6.0-all.jar:/opt/bitnami/spark/jars/clickhouse-jdbc-0.6.0-all.jar

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # Spark Worker 1 UI
    networks:
      - spark-net
    volumes:
      - ./jars/clickhouse-jdbc-0.6.0-all.jar:/opt/bitnami/spark/jars/clickhouse-jdbc-0.6.0-all.jar

networks:
  spark-net:
    driver: bridge
